[window]
padding = { x = 4, y = 2 }
opacity = 0.75
blur = true
startup_mode = "Maximized"

[scrolling]
history = 100000
multiplier = 5

[font]
size = 11.0
offset = { x = 0, y = 4 }
normal = { family = "Hack Nerd Font", style="Regular" }
bold = { family = "Hack Nerd Font", style="Bold" }
italic = { family = "Hack Nerd Font", style="Italic" }
bold_italic = { family = "Hack Nerd Font", style="Bold Italic" }
